server.port=4000

app.version=1.0.0

# app
nestle-api.base-url=${APP_BASE_URL}
app.main.path=${ROOT_PATH}
app.upload.path=${app.main.path}/uploads
nestle-front.base-url=${FRONTEND_BASE_URL}

logging.config=${LOG4J_PATH}

spring.datasource.url=jdbc:postgresql://${DB_URL}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Security
app.http.secure=true
app.http.secure.sameSite=None