server.port=8080

spring.application.name=nestle-api
spring.profiles.active=dev

app.api.path.prefix=/api/v1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Bangkok

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.validation-timeout=10000
spring.datasource.hikari.leak-detection-threshold=15000

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Bangkok

logging.level.com.zaxxer.hikari=debug

spring.mail.from.name=Nescafe
spring.mail.from=noreply@nescafeblendandbrew.com
spring.mail.host=mail.smtp2go.com
spring.mail.port=2525
spring.mail.username=nescafeblendandbrew
spring.mail.password=IeNdXTewhATx97Pu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: Freemarker config
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Security
app.jwt.issuer=nestle-backend-api
app.jwt.audience=nestle-backend
app.jwt.access-ttl-minutes=60
app.jwt.refresh-ttl-days=14
app.jwt.secret=HDCLUXXP7Cx2onmsz0XZahgdBstAxx05
app.http.secure=false
app.http.secure.sameSite=Lax

# Email
app.email.template.claim=claim-link.html.ftl

app.link.expire=2026-03-11,2026-03-13