app.version=1.0.0

# app
nestle-api.base-url=http://localhost:${server.port}
app.main.path=/Volumes/ext_joe/Workspace/MatterInnotech/Projects/Nestle
app.upload.path=${app.main.path}/uploads
nestle-front.base-url=http://localhost:3000

logging.config=classpath:log4j2-dev.xml

# === Database ===
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.woaqbnpkxpmvmiznshpm
spring.datasource.password=7bxxElj8jqw1VF2R
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=1

# Send mail thaibulksms
app.mail.apiKey=uEPWyQq8qIgwYeR5xW3GDuV493cWZX
app.mail.apiSecret=4MpqXFOPonapyJoUHpnxcmHhQYiRS9