app.version=1.0.0

logging.config=${LOG4J_PATH}

spring.datasource.url=jdbc:postgresql://${DB_URL}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Security
app.http.secure=true
app.http.secure.sameSite=None

# service api
nestle-stream-api.url=http://localhost:8081/api/v1